Automated release draft 1
sous-chefs/website pull request #92
Opened 2020-11-28 12:46 UTC by Xorima

## Description

Blog post for Automated Release process

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2020-11-28 13:08 UTC, bmhughes submitted a review, later dismissed

2020-12-01 20:25 UTC, ramereth commented on content/docs/auto-releasing-sous-cookbooks.md
> +We now have cookbooks which are constantly getting updated but moved onto the next problem, releasing these is a manual process which takes time from our variour contributors (Which normally is [Rame
```suggestion
We now have cookbooks which are constantly getting updated but moved onto the next problem, releasing these is a manual process which takes time from our various contributors (Which normally is [Ramereth](https://github.com/Ramereth)).
```

2020-12-01 20:27 UTC, ramereth requested changes, later dismissed
Typos. Should I be concerned about the build failure on circleci?

2020-12-01 20:27 UTC, ramereth commented on content/docs/auto-releasing-sous-cookbooks.md
> +We started to partition the problem into smaller parts, below you can see the architecute we came up with in the end.
```suggestion
We started to partition the problem into smaller parts, below you can see the architecture we came up with in the end.
```

2020-12-01 20:27 UTC, ramereth commented on content/docs/auto-releasing-sous-cookbooks.md
> +Here we truely believe all members of the community should be able to release cookbooks as long as the normal checks (CI, Review) are passed so we did what any DevOps team would do, we built automati
```suggestion
Here we truly believe all members of the community should be able to release cookbooks as long as the normal checks (CI, Review) are passed so we did what any DevOps team would do, we built automation.
```

2020-12-01 20:27 UTC, ramereth commented on content/docs/auto-releasing-sous-cookbooks.md
> +In this architecture we have applications that cover the various problems we forsaw, these are covered in more detail below.
```suggestion
In this architecture we have applications that cover the various problems we foresaw, these are covered in more detail below.
```

2020-12-01 20:27 UTC, ramereth commented on content/docs/auto-releasing-sous-cookbooks.md
> +[Deployment Status Slack Notifier](https://github.com/Xorima/deployment_status_slack_notifier) runs when a [Deployment Status](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#lis
```suggestion
[Deployment Status Slack Notifier](https://github.com/Xorima/deployment_status_slack_notifier) runs when a [Deployment Status](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-deployment-statuses) is updated to Success of Failure. It then route the message to the [Chef Community Slack](https://community-slack.chef.io/). It gets the release notes from the payload of the deployment and posts them to `#Sous-Chefs` and `#Announcements`
```

2020-12-01 20:38 UTC, ramereth commented on content/docs/auto-releasing-sous-cookbooks.md
> +![Sous-Chefs auto release architecture](../images/automation-architecture.png)
```suggestion
![Sous-Chefs auto release architecture](/images/automation-architecture.png)
```

2020-12-04 23:53 UTC, Xorima commented
> Typos. Should I be concerned about the build failure on circleci?

I have no idea, this is the one ci setup I dont know

2021-01-04 22:50 UTC, ramereth commented
> > Typos. Should I be concerned about the build failure on circleci?
> 
> I have no idea, this is the one ci setup I dont know

Yeah it looks like the newer version of hugo doesn't like the theme we use. It needs to be fixed before this can be merged.

2021-11-16 14:41 UTC, merged